// @ts-nocheck
export {};

const BRIDGE_MAP_ENTRIES = [
  {
    renderer: "app:getPlatform",
    gateway: "host:platform",
    appServer: "n/a",
    status: "bridge",
    notes: "返回 Web 运行平台标识。",
  },
  {
    renderer: "app:getVersion",
    gateway: "host:version",
    appServer: "n/a",
    status: "bridge",
    notes: "返回 Web gateway 的版本占位值。",
  },
  {
    renderer: "app:getConfig",
    gateway: "host:config",
    appServer: "n/a",
    status: "bridge",
    notes: "返回 renderer 启动所需的最小运行时配置。",
  },
  {
    renderer: "workspace-root-options",
    gateway: "workspace-root-options",
    appServer: "n/a",
    status: "bridge",
    notes: "返回允许暴露给 Web 的工作区根目录。",
  },
  {
    renderer: "add-workspace-root-option",
    gateway: "add-workspace-root-option",
    appServer: "n/a",
    status: "bridge",
    notes: "把本地项目根目录保存到兼容 Electron globalState 的存储中。",
  },
  {
    renderer: "paths-exist",
    gateway: "paths-exist",
    appServer: "n/a",
    status: "bridge",
    notes: "检查本地路径是否存在，避免项目根目录被误判为已删除。",
  },
  {
    renderer: "workspace-directory-entries",
    gateway: "workspace-directory-entries",
    appServer: "n/a",
    status: "bridge",
    notes: "只列出 allowlist 工作区内的文件目录。",
  },
  {
    renderer: "get-global-state",
    gateway: "get-global-state",
    appServer: "n/a",
    status: "bridge",
    notes: "按 key 返回 renderer 启动所需的最小全局状态。",
  },
  {
    renderer: "set-global-state",
    gateway: "set-global-state",
    appServer: "n/a",
    status: "bridge",
    notes: "把 Electron globalState 风格 UI 状态写回本机 Codex Desktop globalState。",
  },
  // ===== Hover Card / Pinned Threads BEGIN: IPC 映射文档 =====
  // 这三项是官方首页 hover card/pin 会调用的 IPC，实际处理逻辑在下方 handler 中。
  {
    renderer: "list-pinned-threads",
    gateway: "list-pinned-threads",
    appServer: "n/a",
    status: "bridge",
    notes: "读取本地 pinned thread 列表，供首页 hover card/pin 状态使用。",
  },
  {
    renderer: "set-thread-pinned",
    gateway: "set-thread-pinned",
    appServer: "n/a",
    status: "bridge",
    notes: "更新单个 thread 置顶状态并通知 renderer 刷新缓存。",
  },
  {
    renderer: "set-pinned-threads-order",
    gateway: "set-pinned-threads-order",
    appServer: "n/a",
    status: "bridge",
    notes: "保存 pinned thread 拖拽排序后的顺序。",
  },
  // ===== Hover Card / Pinned Threads END: IPC 映射文档 =====
  {
    renderer: "extension-info",
    gateway: "extension-info",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "os-info",
    gateway: "os-info",
    appServer: "n/a",
    status: "bridge",
    notes: "返回运行浏览器宿主机的系统信息。",
  },
  {
    renderer: "is-copilot-api-available",
    gateway: "is-copilot-api-available",
    appServer: "n/a",
    status: "bridge",
    notes: "从 Web bridge 侧报告 Copilot API 是否可用。",
  },
  {
    renderer: "list-automations",
    gateway: "list-automations",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "list-pending-automation-run-threads",
    gateway: "list-pending-automation-run-threads",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "active-workspace-roots",
    gateway: "active-workspace-roots",
    appServer: "n/a",
    status: "bridge",
    notes: "以字符串数组返回当前允许使用的工作区根目录。",
  },
  {
    renderer: "local-environments",
    gateway: "local-environments",
    appServer: "n/a",
    status: "bridge",
    notes: "返回空的本地环境列表，用于兼容 Desktop renderer。",
  },
  {
    renderer: "has-custom-cli-executable",
    gateway: "has-custom-cli-executable",
    appServer: "n/a",
    status: "bridge",
    notes: "报告是否配置了自定义 CLI 可执行文件。",
  },
  {
    renderer: "open-in-targets",
    gateway: "open-in-targets",
    appServer: "n/a",
    status: "bridge",
    notes: "浏览器 gateway 不提供原生打开目标，因此返回空列表。",
  },
  {
    renderer: "native-desktop-app-by-bundle-id",
    gateway: "native-desktop-app-by-bundle-id",
    appServer: "n/a",
    status: "bridge",
    notes: "解析 Desktop 工具/文件行需要的 macOS 应用元数据。",
  },
  {
    renderer: "native-desktop-app-icon",
    gateway: "native-desktop-app-icon",
    appServer: "n/a",
    status: "bridge",
    notes: "返回安全的原生应用图标占位数据，兼容浏览器 renderer。",
  },
  {
    renderer: "open-file",
    gateway: "open-file",
    appServer: "n/a",
    status: "bridge",
    notes: "可预览时返回由 gateway 授权托管的文件 URL。",
  },
  {
    renderer: "get-configuration",
    gateway: "get-configuration",
    appServer: "n/a",
    status: "bridge",
    notes: "为 renderer 配置开关返回保守默认值。",
  },
  {
    renderer: "set-configuration",
    gateway: "set-configuration",
    appServer: "n/a",
    status: "bridge",
    notes: "把 Electron configuration 风格 UI 设置写回本机 Codex Desktop globalState。",
  },
  {
    renderer: "set-remote-control-connections-enabled",
    gateway: "set-remote-control-connections-enabled",
    appServer: "n/a",
    status: "bridge",
    notes: "把远程控制开关同步写回本机 Codex Desktop globalState。",
  },
  {
    renderer: "git-origins",
    gateway: "git-origins",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "inbox-items",
    gateway: "inbox-items",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "ambient-suggestions",
    gateway: "ambient-suggestions",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "ambient-suggestions-refresh",
    gateway: "ambient-suggestions-refresh",
    appServer: "n/a",
    status: "bridge",
    notes: "确认手动刷新 ambient suggestions 的请求。",
  },
  {
    renderer: "projectless-workspace-root",
    gateway: "projectless-workspace-root",
    appServer: "n/a",
    status: "bridge",
    notes: "有可用工作区时返回第一个 allowlist 根目录。",
  },
  {
    renderer: "email-domain-mail-provider",
    gateway: "email-domain-mail-provider",
    appServer: "n/a",
    status: "bridge",
    notes: "为注册流程返回尽力推断的邮箱服务商提示。",
  },
  {
    renderer: "codex-home",
    gateway: "codex-home",
    appServer: "n/a",
    status: "bridge",
    notes: "返回本机 Codex home 路径。",
  },
  {
    renderer: "locale-info",
    gateway: "locale-info",
    appServer: "n/a",
    status: "bridge",
    notes: "返回浏览器宿主机的语言和时区信息。",
  },
  {
    renderer: "projects:list",
    gateway: "projects:list",
    appServer: "n/a",
    status: "bridge",
    notes: "把 allowlist 工作区根目录作为本地项目候选返回。",
  },
  {
    renderer: "projects:browse",
    gateway: "projects:browse",
    appServer: "n/a",
    status: "bridge",
    notes: "只允许浏览 allowlist 工作区内的目录项。",
  },
  {
    renderer: "threads:list",
    gateway: "threads:list",
    appServer: "thread/list",
    status: "bridge",
    notes: "转发到真实 app-server 的 thread/list 方法。",
  },
  {
    renderer: "thread:list",
    gateway: "thread:list",
    appServer: "thread/list",
    status: "bridge",
    notes: "转发到真实 app-server 的 thread/list 方法。",
  },
  {
    renderer: "settings:get",
    gateway: "settings:get",
    appServer: "config/read (for codexConfig)",
    status: "bridge",
    notes: "codexConfig 读 app-server，Electron UI 设置读本机 Desktop globalState。",
  },
  {
    renderer: "settings:set",
    gateway: "settings:set",
    appServer: "config/batchWrite (for codexConfig)",
    status: "bridge",
    notes: "codexConfig 通过明确 edits 写 app-server，Electron UI 设置写本机 Desktop globalState。",
  },
  {
    renderer: "window:setTitle",
    gateway: "window:setTitle",
    appServer: "n/a",
    status: "bridge",
    notes: "在浏览器 shell 内处理。",
  },
  {
    renderer: "shell:openExternal",
    gateway: "shell:openExternal",
    appServer: "n/a",
    status: "bridge",
    notes: "委托给浏览器 window.open。",
  },
  {
    renderer: "codex:initialize",
    gateway: "codex:initialize",
    appServer: "initialize",
    status: "bridge",
    notes: "首次 app-server 握手转发。",
  },
  {
    renderer: "codex_desktop:message-from-view",
    gateway: "codex_desktop:message-from-view",
    appServer: "n/a",
    status: "bridge",
    notes: "浏览器 shell 接收并确认 renderer 发往 host 的消息。",
  },
  {
    renderer: "mcp-request",
    gateway: "mcp-request",
    appServer: "account/read and related MCP methods",
    status: "bridge",
    notes: "把 renderer 发起的 MCP 请求处理后以 mcp-response 返回。",
  },
  {
    renderer: "fetch /wham/accounts/check",
    gateway: "fetch -> /wham/accounts/check",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "fetch /wham/*",
    gateway: "fetch -> ChatGPT backend",
    appServer: "getAuthStatus",
    status: "bridge",
    notes: "由 gateway 使用真实 app-server auth token 代理认证后的 ChatGPT backend 请求。",
  },
  {
    renderer: "fetch /aip/*",
    gateway: "fetch -> ChatGPT backend",
    appServer: "getAuthStatus",
    status: "bridge",
    notes: "由 gateway 使用真实 app-server auth token 代理认证后的 ChatGPT backend 请求。",
  },
  {
    renderer: "account/login/start (via mcp-request)",
    gateway: "mcp-request -> account/login/start",
    appServer: "account/login/start",
    status: "bridge",
    notes: "通过 app-server 转发 account/login/start。",
  },
  {
    renderer: "account/login/cancel (via mcp-request)",
    gateway: "mcp-request -> account/login/cancel",
    appServer: "account/login/cancel",
    status: "bridge",
    notes: "通过 app-server 转发 account/login/cancel。",
  },
  {
    renderer: "config/read (via mcp-request)",
    gateway: "mcp-request -> config/read",
    appServer: "config/read",
    status: "bridge",
    notes: "直接转发 app-server；app-server 不可用时返回真实错误。",
  },
  {
    renderer: "configRequirements/read (via mcp-request)",
    gateway: "mcp-request -> configRequirements/read",
    appServer: "configRequirements/read",
    status: "bridge",
    notes: "可用时从当前 app-server 返回配置要求。",
  },
  {
    renderer: "persisted-atom-sync-request",
    gateway: "persisted-atom-sync",
    appServer: "n/a",
    status: "bridge",
    notes: "host 返回 persisted state 快照。",
  },
  {
    renderer: "persisted-atom-update",
    gateway: "persisted-atom-updated",
    appServer: "n/a",
    status: "bridge",
    notes: "更新会同步写回本机 Codex Desktop 的 persisted atom。",
  },
  {
    renderer: "codex_desktop:get-shared-object-snapshot",
    gateway: "codex_desktop:get-shared-object-snapshot",
    appServer: "n/a",
    status: "bridge",
    notes: "返回本地 shared-object 快照。",
  },
  {
    renderer: "shared-object-set",
    gateway: "shared-object-set",
    appServer: "n/a",
    status: "bridge",
    notes: "更新本地 shared-object 快照。",
  },
  {
    renderer: "shared-object-subscribe",
    gateway: "shared-object-subscribe",
    appServer: "n/a",
    status: "bridge",
    notes: "gateway 确认该订阅请求，用于兼容 renderer。",
  },
  {
    renderer: "codex_desktop:worker:*:from-view",
    gateway: "codex_desktop:worker:*:from-view",
    appServer: "n/a",
    status: "bridge",
    notes: "接收 worker 消息，并在需要时稍后回传响应。",
  },
  {
    renderer: "codex_desktop:worker:*:for-view",
    gateway: "codex_desktop:worker:*:for-view",
    appServer: "n/a",
    status: "bridge",
    notes: "worker 消息订阅通道。",
  },
  {
    renderer: "codex_desktop:system-theme-variant-updated",
    gateway: "codex_desktop:system-theme-variant-updated",
    appServer: "n/a",
    status: "bridge",
    notes: "浏览器主题变化可通过该通道广播。",
  },
  {
    renderer: "codex_desktop:trigger-sentry-test",
    gateway: "codex_desktop:trigger-sentry-test",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
  {
    renderer: "thread:start",
    gateway: "thread:start",
    appServer: "thread/start",
    status: "bridge",
    notes: "尽力映射到 app-server JSON-RPC 方法。",
  },
  {
    renderer: "start-conversation",
    gateway: "start-conversation",
    appServer: "thread/start + turn/start",
    status: "bridge",
    notes: "把 Desktop host 动作适配为真实 app-server 的 thread/turn 请求。",
  },
  {
    renderer: "turn:start",
    gateway: "turn:start",
    appServer: "turn/start",
    status: "bridge",
    notes: "尽力映射到 app-server JSON-RPC 方法。",
  },
  {
    renderer: "turn:interrupt",
    gateway: "turn:interrupt",
    appServer: "turn/interrupt",
    status: "bridge",
    notes: "尽力映射到 app-server JSON-RPC 方法。",
  },
  {
    renderer: "approval:respond",
    gateway: "approval:respond",
    appServer: "approval/respond",
    status: "bridge",
    notes: "尽力映射到 app-server JSON-RPC 方法。",
  },
  {
    renderer: "file:readPreview",
    gateway: "file:readPreview",
    appServer: "file/readPreview",
    status: "bridge",
    notes: "在 gateway 内做 workspace-root 校验后处理。",
  },
  {
    renderer: "file:stat",
    gateway: "file:stat",
    appServer: "file/stat",
    status: "bridge",
    notes: "在 gateway 内做 workspace-root 校验后处理。",
  },
  {
    renderer: "git:status",
    gateway: "git:status",
    appServer: "git/status",
    status: "bridge",
    notes: "先在允许的工作区内尝试本地 git status 兜底，再按需转发 app-server。",
  },
  {
    renderer: "list-archived-threads",
    gateway: "list-archived-threads",
    appServer: "n/a",
    status: "bridge",
    notes: "从本机 Codex Desktop globalState 返回归档会话列表。",
  },
  {
    renderer: "archive-conversation",
    gateway: "archive-conversation",
    appServer: "n/a",
    status: "bridge",
    notes: "在本机 Codex Desktop globalState 中把会话标记为归档。",
  },
  {
    renderer: "unarchive-conversation",
    gateway: "unarchive-conversation",
    appServer: "n/a",
    status: "bridge",
    notes: "从本机 Codex Desktop globalState 的归档列表中移除该会话。",
  },
  {
    renderer: "worktree-delete",
    gateway: "worktree-delete",
    appServer: "n/a",
    status: "bridge",
    notes: "由 gateway 本地处理。",
  },
];

// 官方 bundle 里还有一些不在 codex-bridge-map 中的 Codex 业务 channel，需要显式归属到业务层。
const CODEX_ADDITIONAL_CHANNELS = [
  "account-info",
  "automation-create",
  "automation-delete",
  "automation-run-archive",
  "automation-run-now",
  "automation-update",
  "browser-browsing-data-clear",
  "browser-use-approval-mode-write",
  "browser-use-file-transfer-approval-mode-write",
  "browser-use-file-transfer-origin-add",
  "browser-use-file-transfer-origin-remove",
  "browser-use-history-approval-mode-write",
  "browser-use-origin-add",
  "browser-use-origin-remove",
  "browser-use-origin-state-read",
  "base-branch",
  "chronicle-permissions",
  "current-branch",
  "developer-instructions",
  "experimentalFeature/list",
  "external-agent-import-detect",
  "external-agent-import-status",
  "fast-mode-rollout-metrics",
  "generate-thread-title",
  "get-config-requirements-for-host",
  "get-copilot-api-proxy-info",
  "git-checkout-branch",
  "git-create-branch",
  "gh-cli-status",
  "gh-pr-status",
  "ide-context",
  "install-recommended-skill",
  "list-experimental-features",
  "list-models-for-host",
  "load-recent-conversation-ids-for-host",
  "mcp-codex-config",
  "native-desktop-apps",
  "pick-files",
  "projectless-thread-cwd",
  "read-config",
  "read-config-for-host",
  "read-file-binary",
  "read-file-metadata",
  "recent-branches",
  "recommended-skills",
  "search-branches",
  "set-thread-title",
  "stable-metadata",
  "terminal-shell-options",
  "start-thread-for-host",
  "terminal-attach",
  "terminal-close",
  "terminal-create",
  "terminal-resize",
  "terminal-run-action",
  "terminal-write",
  "transcribe",
  "unwatch-repo",
  "watch-repo",
  "worktree-shell-environment-config",
];

module.exports = {
  BRIDGE_MAP_ENTRIES,
  CODEX_ADDITIONAL_CHANNELS,
};
